Develop
jopnelli/world-holidays pull request #1
Opened 2022-09-12 12:25 UTC by jopnelli

## Summary

The app requires a typed country and an api key to send a request for holidays of the respective country, and render the result in a table. 

App holds input fields and states for the input information, ie the country, the holiday filter and the api key.

If all required information is available, App renders the holiday table, which will fetch, filter and display the holidays for the given parameters. If any information is missing, App will render respective system messages. 

The country input field provides suggestions based on the list of supported countries (saved from the country API endpoint - could implement dynamic refetching to account for changes in the list), validates the input and translates it to the respective country code needed for the fetch request.

The holiday type select field simply filters the fetched list of countries based on the selected holiday type. Since the type query parameter is for paid accounts only, the possible holiday types are hard coded and might be incomplete. 

## Learnings

WOW I have no idea what I'm doing CSS-wise. 

Figuring out when to ask questions is hard. I can apparently figure out everything I wanna do or fix by myself, but it makes things slower. Does that even help me understand things better than hearing it once and then having a reference experience? What's the higher net benefit (knowledge/time)? Also, when I solve it myself, it might work, but it might be sketchy/overly complicated/not best practice. 

Which brings me to the next point: I need to think first. I just start building stuff until something breaks. Then I try things until it works. I rarely take a step back and make a plan. That's also why I don't commit "early and often". I don't incrementally build properly. 

## Struggles

Figuring out the right order of input, validation, query and rendering. Probably also due to not making a plan beforehand, even for a seemingly basic application. 

Also, dealing with CSS, figuring out what commands I need at any given moment. I did buy a course on Udemy though. 

## References

Documentation on https://tanstack.com/query/v4/docs/reference/useQuery

2022-09-12 16:59 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +									const holidayTypeOption = holidayTypeOptions.find(ht => ht.value.includes(t)) || holidayTypeOptions[3];
Holiday type will be "Religious" if no other type fits. Seemed to work for the few countries I tried. I'm aware that that's not clean at all.

2022-09-12 17:00 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +	if(status === "error") return (
Could have added a better error response, eg on "auth failed" a hint to invalid api input.

2022-09-12 17:04 UTC, jopnelli commented on src/components/SearchCountryInputField.tsx
> +		(input.length === 2 && !supportedCountryCodes.includes(input)));
Second validation shouldn't be necessary since the autocomplete will always add full country names from the list of supported countries, and doesn't allow input that doesn't match.

2022-09-13 09:45 UTC, sandrina-p reviewed
@jopnelli I just started the review, but I'm just ~25% there. I'll continue tomorrow, but in the meantime if you could already apply the suggestions I gave it would be highly valuable for both of us!

2022-09-13 09:45 UTC, sandrina-p commented on README.md
> +Requires an API key from Calendarific.
suggestion: A README of a open source project usually has instructions on how to start the project :) Here's [one example](https://www.makeareadme.com/) but you can find many more around the web :)

2022-09-13 09:45 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		return useQuery(["holidays"], async () => {
bug: Can you see the errors in your app? The moment I start the app I got this one:


<details>
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/14869087/189861874-4322e639-289c-456e-91c5-72336532be21.png">
</details>

Errors like these must be fixed otherwise it might lead to bugs later on. Never ignore errors like this, they exist to save your future self from ugly bugs.

And in the terminal, I got these:

<details>

```
[eslint]
src/components/HolidayTable.tsx
  Line 15:10:  React Hook "useQuery" is called in function "getHolidays" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"  react-hooks/rules-of-hooks

Search for the keywords to learn more about each error.
WARNING in [eslint]
src/components/HolidayTable.tsx
  Line 26:5:  React Hook useEffect has a missing dependency: 'refetch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

src/components/SearchCountryInputField.tsx
  Line 28:5:  React Hook useEffect has a missing dependency: 'setSearchCountry'. Either include it or remove the dependency array. If 'setSearchCountry' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps

ERROR in [eslint]
src/components/HolidayTable.tsx
  Line 15:10:  React Hook "useQuery" is called in function "getHolidays" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"  react-hooks/rules-of-hooks

Search for the keywords to learn more about each error.

webpack compiled with 1 error and 1 warning
No issues found.
```
</details>

2022-09-13 09:45 UTC, sandrina-p commented on src/App.tsx
> +	const [apiKey, setApiKey] = useState("");
question: What editor do you use? Do you use Tabs or Spaces? Is in your local machine the indentation like in here?

<details>
<img width="678" alt="image" src="https://user-images.githubusercontent.com/14869087/189863512-2c174de4-64b9-43ed-90be-fa368b99a618.png">


</details>

2022-09-13 09:45 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		}, {enabled: false, onSuccess: setHolidayData});
When using reactQuery, you must pass variables as query parameters, so the cache works properly.

Another thing you can do is to cache the results so it doesn't do extra requests. For that, you need to configure one thing in react query called `staleTime`

References: (docs)
- Video Tutorial: Query by id: https://www.youtube.com/watch?v=2s2iJLLDwgk&ab_channel=Codevolution
- Docs: Query keys: https://react-query.tanstack.com/guides/query-keys
- https://youtu.be/2TX8ojaSwF0 (cache)
- https://youtu.be/0BtcMLJ_Zdc (stale time)
- https://tkdodo.eu/blog/practical-react-query#the-defaults-explained - read the part about defaults

2022-09-13 09:45 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		<SystemMessage
todo: My first request: Let's organize this code better. The project only has 5 files and each one is huge. It's hard to understand there data flow starts and ends. Here's my suggestion:

- Create folder for each smaller component.
- Move "types" related to each component to its own folder
- Move styles related to each component to its own folder

Something like this:

```
components/
  MyComponent
      index.tsx
      MyComponent.tsx
      MyComponent.styled.tsx
      MyComponent.types.ts
```

Reference: https://www.joshwcomeau.com/react/file-structure/

Among other things, this will help you maintain the codebase and "test" things individually and it will help me give better code reviews.

2022-09-13 09:45 UTC, sandrina-p commented on package.json
> +  "eslintConfig": {
question: Do you have ESLint configured in your project and vscode? I mean, when you save the file, does it auto-formats it? I don't think so because I spot multiple places with indentations errors.

Reference: https://www.youtube.com/watch?v=xinJSYiOB6Q&ab_channel=Olli

2022-09-13 09:45 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +									const holidayTypeOption = holidayTypeOptions.find(ht => ht.value.includes(t)) || holidayTypeOptions[3];
_Make it work, then make it better!_

You really fancy variables with one character :p I have a question: Why did you decide to make `holidayTypeOptions` an array instead of an object? Don't you think it would make it more readable here? Or create two types: One object, and then one array based on the object.

2022-09-14 06:02 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +		return useQuery(["holidays"], async () => {
That's weird, I didn't get either of those. Not sure what my Eslint is doing.

2022-09-14 06:05 UTC, jopnelli commented on src/App.tsx
> +	const [apiKey, setApiKey] = useState("");
I use IntelliJ, and tabs. It looks like this for me: 

![Screenshot 2022-09-13 at 13 44 48](https://user-images.githubusercontent.com/98757323/190072406-d7424620-c11d-4dc6-bccf-b2a4a6262e7f.png)

(Also can't figure out how to put this screenshot in <details> rn)

2022-09-14 06:06 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +									const holidayTypeOption = holidayTypeOptions.find(ht => ht.value.includes(t)) || holidayTypeOptions[3];
I think I did that because it's the OptionsType for react-select. And then didn't think about it anymore. You're right, I get the readability issue

2022-09-14 06:08 UTC, jopnelli commented on package.json
> +  "eslintConfig": {
It should be so that it uses the eslint project file - and it does auto-format, yes.

2022-09-14 08:41 UTC, jopnelli commented on package.json
> +  "eslintConfig": {
I'll rewatch the video and try to figure it out.

2022-09-14 08:42 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +		}, {enabled: false, onSuccess: setHolidayData});
I can't seem to figure out how to get the cache to work right now. I'll try to be back at it tonight.

2022-09-14 13:43 UTC, sandrina-p commented on src/App.tsx
> +	const [apiKey, setApiKey] = useState("");
You do it like this:

```

<details>

your text inside, anything here will be collapsed.

</details>


````

2022-09-14 13:44 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		return useQuery(["holidays"], async () => {
Probably is because you use IntelliJ. I'm not familiar with it, so maybe [these docs](https://www.jetbrains.com/help/idea/prettier.html#ws_prettier_apply_code_style) can help?

2022-09-14 13:44 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		return useQuery(["holidays"], async () => {
In your terminal when you run the project, don't you see any logs? That's super weird. If needed we can do a video call so that I can help you :)

2022-09-14 13:45 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		}, {enabled: false, onSuccess: setHolidayData});
It does not work because you are using the useQuery incorrectly as shown in the [log errors above](https://github.com/jopnelli/world-holidays/pull/1#discussion_r969361591) ;) If you fix those, then it will be easier to fix these too.

2022-09-14 13:47 UTC, sandrina-p commented on package.json
> +  "eslintConfig": {
Now that I know you use InteliJ, I believe it's because you and I have different default editor configs. You must set a `.editorconfig` at the root of your project with the configs you wish to use. Learn more at: https://editorconfig.org/

2022-09-14 15:38 UTC, jopnelli commented on package.json
> +  "eslintConfig": {
I have disabled EditorConfig - but have now (I think) fixed ESLint and Prettier and will include the ESLint file in the next commit, so hopefully it'll be working for you then.

2022-09-14 15:41 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +		}, {enabled: false, onSuccess: setHolidayData});
I have fixed the rules-of-hooks error, and added the variables to the query key as described in the documentation. Me not getting cached data couldn't really be related to setSearchCountry not being included in the dependency array, could it?

2022-09-14 15:43 UTC, jopnelli commented on src/App.tsx
> +	const [apiKey, setApiKey] = useState("");
I got "bullied" into using it by colleagues, mainly the tech lead. Apparently everybody at the company uses IntelliJ - and he got frustrated helping me fix stuff on VSCode. I liked VSCode a lot tbh, but going with IntelliJ seemed to be the easier, more diplomatic path.

2022-09-14 15:44 UTC, jopnelli commented on src/App.tsx
> +	const [apiKey, setApiKey] = useState("");
> You do it like this:
> 
> ```
> 
> <details>
> 
> your text inside, anything here will be collapsed.
> 
> </details>
> ```

I tried that, but could only get the link as text.

<details> 
![Screenshot 2022-09-13 at 13 44 48](https://user-images.githubusercontent.com/98757323/190200999-86c28eb2-e83b-4700-a85f-675bb67714df.png)
</details>

2022-09-14 15:54 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +		return useQuery(["holidays"], async () => {
I do get logs at times, also from ESLint - but didn't get the ones you shared (react-hooks/rules-of-hooks, react-hooks/exhaustive-deps). Because I didn't have the eslint-plugin-react-hooks installed... The more you know.

2022-09-14 20:25 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		return useQuery(["holidays"], async () => {
Humm... that doesn't make sense. How have you installed all dependencies in this project `npm run install` or something else? (P.S. I shared a Loom with you on discord, check it before answering this comment)

2022-09-14 20:27 UTC, sandrina-p commented on src/App.tsx
> +	const [apiKey, setApiKey] = useState("");
Oh, gotcha. Well, that sucks (the bully part). Feel free to do whatever makes you the most comfortable in your job :) 


Regarding details, it's missing the empty extra line between the tag and the image ;)  In markdown, empty lines make the difference!

2022-09-14 20:29 UTC, sandrina-p commented on package.json
> +  "eslintConfig": {
Why have you disabled EditorConfig? It's essential to ensure consistency among different OS and editors like you and me :) Perhaps you can enable it for just a given set of projects. Or adding `.editorconfig` file is enough to enable it in this project

2022-09-14 20:47 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		}, {enabled: false, onSuccess: setHolidayData});
I must confess that it took me a while to understand why it was not working, and I had to install `react-query/devtools` to figure out why. That's my hint for you. Install it you'll see why :p 

Here some more hints: (Read only after you installed the tool!

<details>
- Hint 1: Have you noticed that the react-query debug/logo disappears when there are no results?

<details>
- Hint 2: Check the renders. Have you noticed that react-query is not executed (rendered) while there are no results?

<details>
- Answer: react-query must be rendered always to be able to cache the data. That's why it's recommended you set it at top level, at app.js. Otherwise when it unmounts, the cached data is gone too.
</details>
</details>

</details>

2022-09-14 20:54 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +    return (
Nice skeleton effect! Now, when this happens, you are re-rendering the entire table (and duplicate some chunks of code). Can you refactor this so the loading state only affects the `<tbody>` part?

Perhaps you don't know this, but you can include ternanies inside a return, like this:

```js
<div>
  {status === "loading" ? (
    <div>
      <p>is loading</p>
    </div>
  ) : (
    <p>content loaded!</p>
  )}
</div>

2022-09-14 21:07 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +  const { status } = useQuery(
Interesting way you found here to use `react-query`. So, you are using it to get the `status`, but then use onSuccess + useState + useMemo just to retrieve the data. 3 re-renders just for the initial load.

In the docs you can see the entire [useQuery API spec](https://react-query-v3.tanstack.com/reference/useQuery), and you'll notice a couple of things that make your life easier:

- `isLoading` and `isError` - to get the current status
- `data` - to get the `data` replacing `setHolidayData`
- `select` - to transform the promise result and send it to `data`, replacing useMemo.

It's something like this:

```js
  const { data: holidayData, isLoading, isError } = useQuery(..., {
      select: (data) => { /* do similar as filteredHolidays */}
  })
  ```

2022-09-14 21:10 UTC, sandrina-p commented on src/components/ApiKeyInput/ApiKeyInput.styled.tsx
> +import { InputFieldStyled } from "../CountrySearchField/SearchCountryInputField.styled";
I have some questions to make you think:

1. Visually speaking, what's the difference between ApikeyInput and SearchCountryInputField? (besides autocomplete)
2. What's the difference between  ApikeyInput and a normal Input?
3. Did you find it weird to import styles from another "business" component?
4. Have you thought about having a `<FieldInput>` that both API and search inputs consume?

2022-09-15 07:59 UTC, jopnelli commented on src/components/ApiKeyInput/ApiKeyInput.styled.tsx
> +import { InputFieldStyled } from "../CountrySearchField/SearchCountryInputField.styled";
1. & 2.: One is a "typing" input field, and one is an "insert" (ie copy paste) one? You're saying that should probably be clearer in styling, right?

3. & 4.: Yes and yes. I couldn't decide where to put it (ie what's best practice for folder structure of shared styled components) on the spot, so I just went with the weird choice.

2022-09-15 08:09 UTC, sandrina-p commented on src/components/ApiKeyInput/ApiKeyInput.styled.tsx
> +import { InputFieldStyled } from "../CountrySearchField/SearchCountryInputField.styled";
1. I asked visually speaking. You answered based on features. So visually speaking they are the same :p
2. When it comes to file structures, [don't overthink it](https://reactjs.org/docs/faq-structure.html). It's a small project, so a flat structure is totally okay here :). `components/Input` is enough :)

2022-09-15 08:23 UTC, jopnelli commented on package.json
> +  "eslintConfig": {
It's disabled because the config formatting from my IDE conflicts with Prettier / ESLint. I never set up the Code Style in the IDE, and just using the ESLint / Prettier seemed to work so far.

2022-09-15 11:03 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +		return useQuery(["holidays"], async () => {
I've installed dependencies via `npm install`. I don't know what caused it. I now removed the dependencies, deleted node_modules and package-lock.json, reinstalled, now it works as you described.

2022-09-15 11:42 UTC, jopnelli commented on src/components/HolidayTable.tsx
> +		}, {enabled: false, onSuccess: setHolidayData});
My goodness. I refactored it bit, but it doesn't seem to be working with enabled set to false initially either. Not sure rn how else I'll wait for user input without running the query instantly (which results in 401, since no variables are passed).

2022-09-16 13:37 UTC, sandrina-p commented on src/components/HolidayTable.tsx
> +		return useQuery(["holidays"], async () => {
That isn't very odd. Many times in the node world, we'll need to restart node_modules for many mystery reasons

2022-09-16 13:39 UTC, sandrina-p commented on package.json
> +  "eslintConfig": {
> I never set up the Code Style in the IDE, and just using the ESLint / Prettier seemed to work so far.

You'll need that we working with people that don't have the same configs as you. It's better than you manage a way to work with local configs (like this project) and global configs (for your computer only)

2022-09-16 14:33 UTC, sandrina-p requested changes
Looking good, some more things to say!

2022-09-16 14:33 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.styled.tsx
> +  border: 1px solid #c5cfdc;
Have you ever worked in some type of design system or a simple `theme.jsx` file? That place is where you declare the common "tokens" of a project, such as colors, typography, breakpoints, etc...

I suggest you give it a try in this project. You could use `styled-components` theme directly, or try native CSS - CSS Variables. Organize your project like this:

There are many ways to organize (and name) CSS variables, this is just a simple yet effective way:

```css
html {
  --colors-brand: #00000;
  --colors-bakckground: #00000;
  --colors-text_normal: #00000;
  --colors-text_light: #00000;
  --colors-danger: #00000;
  --colors-success: #00000;
  --....
 
  /* t-shirt size */
  --text-xl: 2rem;
  --text-lg: 1.5rem;
  --text-md: 1rem;
  ...
}

```

With this in place, you can even add [a dark theme](https://epicreact.dev/css-variables/). Give it a try :)

2022-09-16 14:33 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +            : data!.map((h, i) => {
question: Why do you need this `data!.map` here?

2022-09-16 14:33 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +function removeDuplicateHolidays(holidays: HolidayItem[]) {
This is okay here because the file is still small. But when it gets bigger, remember to use `HolidayTable.helpers.tsx` ;)

2022-09-16 14:33 UTC, sandrina-p commented on src/App.tsx
> +      <ApiKeyInput
bonus: Each time I refresh the page, I need to set the API key again. Do you know `localStorage`? You could store it there to persist across page reloads ;)

2022-09-16 14:33 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +  if (holidayTypeFilterValues.includes("Religious")) {
question: Why do you exclude non religious here? The code isn't that self-explanatory here. In these cases, it's always good to leave a code comment explaining it.

2022-09-16 14:33 UTC, sandrina-p commented on src/components/HolidayTypeFilter/HolidayTypeSelectField.tsx
> +  const colourStyles: StylesConfig<HolidayType> = {
these are styles, so it could be moved to the `styled.tsx` file :)

2022-09-16 14:33 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +                              color={holidayTypeOption.color}
mini bug: Have you noticed that the HTML has `<span color="#xxxx">`? That's because you are using a prop for styling, but not for the DOM. That's what SC call [Transient props](https://styled-components.com/docs/api#transient-props). In this case it should be `$color`.

2022-09-16 14:33 UTC, sandrina-p commented on src/components/CountrySearchField/SearchCountryInputField.tsx
> +      {suggestionsListComponent}
bug: This is a code smell, react doesn't scream at you but this type of "react component" is not really a react component, and react won't be able to do any type of performance/memoization between re-renders (also called as [reconciliation](https://reactjs.org/docs/reconciliation.html).

Please refactor this to use a proper `<SuggestionsList />` component :)

2022-09-16 14:33 UTC, sandrina-p commented on src/App.tsx
> +    isValid: false,
Do you really need `isValid` here? AFAIK, an empty code is the same as isValid: false. That logic can be simplified to just the text directly ;)

2022-09-16 14:33 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +      enabled: isEnabled,
Same here, this `isEnabled` might not be needed. It's the same as `!!country`, right? :)

2022-09-16 14:37 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +import { holidayTypeOptions } from "../HolidayTypeFilter/HolidayTypeSelectField";
todo: Whenever you see yourself importing a non-component from a component file, that's a code smell. It means it should be at `HolidayTypeSelectField.helpers.tsx` or even at another place like `src/data/holidays.tsx`, and then inside you have everything related to the api/services/data

2022-09-16 14:46 UTC, sandrina-p commented on src/App.tsx
> +        setApiKey={setApiKey}
Let's look at this `setApiKey` pattern:
Here we pass the `setApiKey` as prop to inside the compone, and then update the parent state from the inside children. What if we could simplify that?

Let's recap what we need here: Update the parent state when the input value changes.

Here's my suggestion: Remove logic from the child component and move it to the parent, taking the _data responsibility_ away from _dumb components_. Like this:

```tsx
<ApiKeyInput onChange={(value) => setApiKey(value)} />

```

```tsx

// ApiKeyInput.tsx
      <ApiKeyInputFieldStyled
        // ....
        // onChange={(e) => setApiKey(e.currentTarget.value)}
        onChange={onChange}
      />

```

Then each child component only has one prop to call it immediately:

You can apply this in the other 2 input fields at the top, and you'll notice it gets easier to understand the data flow from the parent component. WDYT? Does this pattern make sense to you?

2022-09-16 14:53 UTC, sandrina-p commented on src/App.tsx
> +const Container = styled.div`
CSS challenge: In a smaller screen the API Key is not visible. 
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/14869087/190668192-7c58ba5d-eade-4a87-a37f-a6abe47359fd.png">

Can you make it _always_ visible at the bottom of the screen using display or grid? (without using position: absolute)

2022-09-16 14:56 UTC, sandrina-p commented on README.md
> +
When you publish the website, you can add the link here!

(P.S. Assuming this won't have many visits, you could add a description to the apikey input with your own key for folks in the web use it right away :p )

2022-09-17 19:20 UTC, jopnelli commented on src/components/CountrySearchField/SearchCountryInputField.tsx
> +      setAutocompleteState({
That's my bad, I just didn't write the `isActive` styling. The selection by arrow keys works. Fixed it now.

2022-09-17 19:33 UTC, jopnelli commented on src/components/HolidayTable/HolidayTable.tsx
> +            : data!.map((h, i) => {
Because I didn't bother to avoid `Object is possibly 'undefined'.` 🫣  Can you give me a hint on what would be a better practice?

2022-09-17 19:49 UTC, jopnelli commented on src/App.tsx
> +      <ApiKeyInput
I fixed it, but now I'm passing the API key outward to App, just to receive it again as defaultValue. Trying to figure out a better solution other than keeping additional local state.

2022-09-18 13:59 UTC, jopnelli commented on src/App.tsx
> +        setApiKey={setApiKey}
Yeah that makes sense. For the API key component, I'm now still passing the apiKey state (since I'm setting it from local storage via onChange, but also want to set it as defaultValue). Would it be better to keep a local state than pass the value out just to receive it again? ([Related comment](https://github.com/jopnelli/world-holidays/pull/1#discussion_r973621847))

2022-09-18 14:30 UTC, jopnelli commented on src/components/HolidayTable/HolidayTable.tsx
> +  if (holidayTypeFilterValues.includes("Religious")) {
Ah so while I only filter for four holiday types, each type can include multiple values (eg "Common local holiday", "local holiday" for type "Local"). The api doesn't return the overarching category explicitly (it only offers that via paid account and query string).

So I tested some countries and added the values for the holiday types except religious, because that had the most values.

So now when the selected type is religious, I exclude all values of the other types, and see if there are still values left - then that would be counted as religious. (I'm aware that's not a perfectly clean solution..)

2022-09-20 07:28 UTC, sandrina-p commented on src/App.tsx
> +      <ApiKeyInput
This is a case where TS screams at us for "precaution", but we know it won't ever happen because of `getFilteredHolidays` (at most, inside that fn you can do `if(!holidayData) { return [] }` to ensure and empty array).

So, back to this file, you can do the following:

```diff
  if (isError) return <SystemMessage type={SystemMessageType.ERROR} />;

+  if (!data) return <SystemMessage type={SystemMessageType.RESULTS_EMPTY} />;
```

P.S. `EMPTY` could be renamed to `COUNTRY_EMPTY` :)

2022-09-20 07:35 UTC, sandrina-p commented on src/components/HolidayTable/HolidayTable.tsx
> +  if (holidayTypeFilterValues.includes("Religious")) {
I see... can you tell me which countries you noticed this part where it includes multiple values? Because, accordingly to the [API docs](https://calendarific.com/api-documentation), it can only return these:



`type` | We support multiple types of holidays and observances. This parameter allows users to return only a particular type of holiday or event. By default, the API returns all holidays. Below is the list of holiday types supported by the API and this is how to reference them.
- `national` - Returns public, federal and bank holidays
- `local` - Returns local, regional and state holidays
- `religious` - Return religious holidays: buddhism, christian, hinduism, muslim, etco
- `bservance`- Observance, Seasons, Times

2022-09-20 08:10 UTC, sandrina-p commented on src/components/SystemMessage/SystemMessage.styled.tsx
> +  height: 80%;
todo: I sent you a Loom on discord about these hardcoded heights ;)

2022-09-21 09:57 UTC, jopnelli commented on src/components/HolidayTable/HolidayTable.tsx
> +  if (holidayTypeFilterValues.includes("Religious")) {
My goodness I just realized that in a clouded moment I read the documentation wrong: "Please note that **some** of the optional parameters are only limited to paid users."

And just went on assuming that the type query is for paid users only. That's why I'm not fetching prefiltered, but fetching all holidays and doing the filtering by type manually.

So while the actual names of the holiday types fall under these four categories, the names are returned as eg "buddhism" as opposed to "religious" - so I have to filter for the values, that I collected and added under the category myself. Silly...

2022-09-25 11:53 UTC, jopnelli commented on src/App.tsx
> +            {/*<ThemeSwitchButton />*/}
Because I didn't actually implement any theme, so the button only switches styling on itself.

2022-09-25 12:04 UTC, merged